COVE/urls.py
from django.conf.urls import patterns, include, url
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

# Uncomment the next two lines to enable the admin:
# from django.contrib import admin
# admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'COVE.views.home', name='home'),
    # url(r'^COVE/', include('COVE.foo.urls')),

    # Uncomment the admin/doc line below to enable admin documentation:
    # url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    # url(r'^admin/', include(admin.site.urls)),
	url(r'^edit_colony/', include( 'edit_colony.urls')),
	#url(r'^static/(?P<path>.*)$', 'django.views.static.serve', {'document_root': settings.STATIC_ROOT }),
	url(r'^viz/', include( 'viz.urls')),
	url(r'^home/', include( 'home.urls')),
    url(r'^menu/', include( 'menu.urls')),
    url(r'^register/', include( 'registrations.urls')),
    url(r'^breeding_calculator/', include( 'breeding_calculator.urls')),
)

urlpatterns += staticfiles_urlpatterns()

edit_colony/urls.py
from django.conf.urls import patterns, url
from edit_colony import views

urlpatterns = patterns('', 
	url(r'validate_mouse/?$', views.validate_mouse, name='validate_mouse'), 
	url(r'edit_mouse/?$', views.edit_mouse, name='edit_mouse'), 
	url(r'find_edit/?$', views.find_edit, name='find_edit'),
	url(r'add_mouse/?$',views.add_mouse,name="add_mouse"),
)

viz/urls.py
from django.conf.urls import patterns, url
from viz import views

urlpatterns = patterns('',
    url(r'find_lineage/?$', views.find_lineage, name='find_lineage'),
	 url(r'lineage_view/?$', views.draw_lineage, name='lineage'),
    url(r'force_view/?$', views.draw_force, name='force'),
    url(r'pack_view/?$', views.draw_pack, name='pack'),
    url(r'colony/?$', views.draw_colony, name='colony'),
    url(r'stats/?$', views.draw_stats, name='stats'),
)

mice_db/models.py
from django.db import models

# Create your models here.
# The path to this file needs to exist in the main settings.py
# and then running 'python manage.py syncdb' will create the tables

class Mouse(models.Model):
	mouseId = models.CharField(max_length=15, primary_key=True)
	colonyId = models.ForeignKey('Colony', blank=True, null=True, on_delete=models.SET_NULL)
	generation = models.IntegerField(default=0)
	gender = models.CharField(max_length=5)
	litter = models.IntegerField(default=0)
	fatherId = models.CharField(max_length=15, blank=True)
	motherId = models.CharField(max_length=15, blank=True)
	dobMonth = models.IntegerField(null=True, blank=True)
	dobDay = models.IntegerField(null=True, blank=True)
	dobYear = models.IntegerField(null=True, blank=True)
	dodMonth = models.IntegerField(null=True, blank=True)
	dodDay = models.IntegerField(null=True, blank=True)
	dodYear = models.IntegerField(null=True, blank=True)
	tod = models.CharField(max_length=15, blank=True)
	notes = models.TextField(blank=True)
	gene1 = models.CharField(max_length=10)
	gene2 = models.CharField(max_length=10)
	gene3 = models.CharField(max_length=10)
	genotype1 = models.CharField(max_length=10)
	genotype2 = models.CharField(max_length=10)
	genotype3 = models.CharField(max_length=10)

	def __unicode__(self):
		return self.mouseId

class Colony(models.Model):
	colonyId = models.IntegerField(primary_key=True)
	createdDate = models.DateField(auto_now_add=True)

class Genotype(models.Model):
	name = models.CharField(max_length=10)

edit_colony/views.py
# Create your views here.
import json
from django.http import HttpResponse
from django.shortcuts import render
from django import forms
from django.core.exceptions import ObjectDoesNotExist
from mice_db.models import Mouse, Genotype

class MouseEditForm( forms.ModelForm):
	class Meta:
		model = Mouse
		widgets = {
			'notes': forms.Textarea(attrs={'cols': 80, 'rows': 5}),
			'gene1': forms.Select(attrs={'class': "easyui-combobox",
						'name':"gene1"}),
			'gene2': forms.Select(attrs={'class': "easyui-combobox",
						'name':"gene2"}),
			'gene3': forms.Select(attrs={'class': "easyui-combobox",
						'name':"gene3"}),
			'genotype1': forms.RadioSelect(
						choices=[("+/-", "+/-"), ("-/-", "-/-"),
								("WT", "+/+(WT)"), ("NA", "NA")]),
			'genotype2': forms.RadioSelect(
						choices=[("+/-", "+/-"), ("-/-", "-/-"),
								("WT", "+/+(WT)"), ("NA", "NA")]),
			'genotype3': forms.RadioSelect(
						choices=[("+/-", "+/-"), ("-/-", "-/-"),
								("WT", "+/+(WT)"), ("NA", "NA")]),
		}

def mouse_context( gene1Val='',
				   gene2Val='',
				   gene3Val='',
				   submitAction='/edit_colony/add_mouse/',
				   header='Please correct the following errors'):
	allVars = {}
	gTypes = []
	for t in Genotype.objects.all():
		gTypes.append(t.name)
	allVars['geneList'] = gTypes
	allVars['gene1Val'] = gene1Val
	allVars['gene2Val'] = gene2Val
	allVars['gene3Val'] = gene3Val
	allVars['submitAction'] = submitAction
	allVars['header'] = header
	return allVars


def mousee_context( gene1Val='',
				   gene2Val='',
				   gene3Val='',
					submitAction='/edit_colony/validate_mouse/',
					header='Please correct the following errors'):
	allVars = {}
	gTypes = []
	for t in Genotype.objects.all():
		gTypes.append(t.name)
	allVars['geneList'] = gTypes
	allVars['gene1Val'] = gene1Val
	allVars['gene2Val'] = gene2Val
	allVars['gene3Val'] = gene3Val
	allVars['submitAction'] = submitAction
	allVars['header'] = header
	return allVars

def validate_mouse(request):
	if request.method == 'POST':
		valid = True
		form_errors=MouseEditForm(request.POST)
		if request.POST["mouseId"]:			
			try:
				dbEntry = Mouse.objects.get(mouseId=request.POST["mouseId"])
				form_errors.errors['mouseId'] = \
				"Mouse ID already in use - enter new ID"
				valid = False
			except Mouse.DoesNotExist:
				valid=True
		if request.POST["fatherId"]:
			try:
				father = Mouse.objects.get(mouseId=request.POST["fatherId"])
				if father.gender == 'F':
					form_errors.errors['fatherId']= \
					"Father specified is a female. Please enter correct father."
					valid = False
			except Mouse.DoesNotExist:
				form_errors.errors['fatherId']= \
				"Father does not exist in colony. Please enter valid father."
				valid = False
		if request.POST["motherId"]:
			try:
				mother = Mouse.objects.get(mouseId=request.POST["motherId"])
				if mother.gender == 'M':
					form_errors.errors['motherId']= \
					"Mother specified is a female. Please enter valid mother."
					valid = False
			except Mouse.DoesNotExist:
				form_errors.errors['motherId']=\
				"Mother does not exist in colony. Please enter valid mother."
				valid = False
		#if form_errors.is_valid():
		if valid == True:
			form_errors.save()
			return HttpResponse("Saved mouse data")
		else:
			contextVars=mousee_context()
			contextVars['form'] =  form_errors
			return render(request, 'validate_mouse.html',contextVars)
	form = MouseEditForm()
	contextVars=mousee_context()
	contextVars['form']=form
	return render(request, 'validate_mouse.html', contextVars)







def add_mouse(request):
	if request.method == 'POST':
		# Bind POST data to form obj and associate with row in db
		if request.POST["mouseId"]:
			try:
				dbEntry = Mouse.objects.get( mouseId=request.POST["mouseId"] )
				# This mouseId is already in use - send error
				form = MouseEditForm( request.POST)
				form.errors['mouseId'] = \
				"Mouse ID already in use - enter a new ID"
				contextVars = mouse_context()
				contextVars['form'] = form
				return render( request, 'add_mouse.html', contextVars)
			except Mouse.DoesNotExist:
				form = MouseEditForm( request.POST)
				if form.is_valid():
					form.save()
					return HttpResponse("Saved mouse data")
				else:
					return HttpResponse("Form did not validate")
	# Default response for form request
	form = MouseEditForm()
	# Supply list of used genotypes
	contextVars = mouse_context()
	contextVars['form'] = form
	return render( request, 'add_mouse.html', contextVars)

def edit_mouse(request):
	if request.method == 'POST':
		# Bind POST data to form obj and associate with row in db
		if request.POST["mouseId"]:
			try:
				dbEntry = Mouse.objects.get( mouseId=request.POST["mouseId"] )
				form = MouseEditForm( request.POST, instance=dbEntry)
				if form.is_valid():
					form.save()
					return HttpResponse("Saved mouse data")
				else:
					# Return form with error messages
					contextVars = mouse_context()
					contextVars['form'] = form
					return render( request, 'edit_mouse.html', contextVars)
			except Mouse.DoesNotExist:
				form = MouseEditForm( request.POST)
				form.errors['mouseId'] = \
				"MouseId does not match an existing mouse"
				contextVars = mouse_context()
				contextVars['form'] = form
				return render( request, 'edit_mouse.html', contextVars)
	elif request.method == 'GET':
		mId = request.GET["mouseId"]
		try:
			dbEntry = Mouse.objects.get( mouseId=mId )
			form = MouseEditForm( instance=dbEntry)
			contextVars = mouse_context(
							gene1Val=dbEntry.gene1,
							gene2Val=dbEntry.gene2,
							gene3Val=dbEntry.gene3,
							submitAction='/edit_colony/edit_mouse/',
							header='Edit mouse')
			contextVars['form'] = form
			return render( request, 'edit_mouse.html', contextVars)
		except Mouse.DoesNotExist:
			return HttpResponse("The mouse ID was not found in the database")
	# Default response for form request
	form = MouseEditForm()
	# Supply list of used genotypes
	contextVars = mouse_context(submitAction='/edit_colony/edit_mouse/',
								header='Enter a mouse ID')
	contextVars['form'] = form
	return render( request, 'edit_mouse.html', contextVars)

def find_edit(request):
#       if request.method == 'POST':
#   		# Bind POST data to form obj and associate with row in db
#   		if request.POST["mouseId"]:
#   			try:
#   				dbEntry = Mouse.objects.get( mouseId=request.POST["mouseId"] )
#   				form = MouseEditForm( instance=dbEntry)
#   				contextVars = mouse_context(
#   								submitAction='/edit_colony/edit_mouse/',
#   								header='Edit mouse')
#   				contextVars['form'] = form
#   				return render( request, 'edit_mouse.html', contextVars)
#   			except Mouse.DoesNotExist:
#   				form = MouseEditFind()
#   				form.errors['mouseId'] = "The mouse ID was not valid"
#   				return render( request, 'find_mouse.html', {
#   					'form': form,
#   					})
#   		else:
#   			form = MouseEditFind()
#   			form.errors['mouseId'] = "A mouse ID is required"
#   			return render( request, 'find_mouse.html', {
#   				'form': form,
#   				})
	# Default
	return render( request, 'find_edit.html', {
		'iSrc':"/edit_colony/edit_mouse/",
	})

viz/views.py
# Create your views here.
from django.shortcuts import render
from django import forms
import viz.data_retrieval as vizd
from django.core.exceptions import ObjectDoesNotExist
from mice_db.models import Mouse
from django.http import HttpResponse

class MouseEditFind(forms.Form):
    mouseId = forms.CharField(max_length=15)


def draw_lineage(request):
    #if request.method == "POST":
    #    if request.POST["mouseId"]:
    #        json_lineage = nodelink.get_json_lineage(request.POST["mouseId"])
    #        contextVars = {'json_lineage': json_lineage}
    #        return render(request, 'lineage_view.html', contextVars)
    ## Default response for form request
    #form = MouseEditFind()
    #contextVars = {'form': form}
    #return render(request, 'find_lineage.html', contextVars)

    if request.method == "GET":
        try:
            dbEntry = Mouse.objects.get( mouseId=request.GET["mouseId"])
            json_lineage = vizd.get_json_lineage(request.GET["mouseId"])
            contextVars = {'json_lineage': json_lineage,
                           'iSrcEdit':"/edit_colony/edit_mouse/",
                           'curr_domain': request.get_host(),
            }
            return render(request, 'lineage_view.html', contextVars)
        except Mouse.DoesNotExist:
            return HttpResponse("The mouse ID was not found in the database")

def find_lineage(request):

    return render( request, 'find_lineage.html', {
        'iSrc':"/viz/lineage_view/",
    })

def draw_force(request):
    if request.method == "GET":
        # Need data of all mice in json format
        jsonAllMice = vizd.all_mice_gen()
        contextVars = {'jsonAllMice': jsonAllMice}
        return render(request, 'force_view.html', contextVars)

def draw_pack(request):
    if request.method == "GET":
        # Need data of all mice in json format
        jsonAllMice = vizd.all_mice_gen()
        contextVars = {'jsonAllMice': jsonAllMice,
					   'curr_domain': request.get_host()}
        return render(request, 'pack_view.html', contextVars)

def draw_colony(request):
    if request.method == "GET":
        # Need data of all mice in json format
        jsonAllMice = vizd.all_mice_gen()
        contextVars = {'jsonAllMice': jsonAllMice,
					   'curr_domain': request.get_host(),
                  'viewSelection': 'colony'}
        return render(request, 'colony.html', contextVars)

def draw_stats(request):
    if request.method == "GET":
        # Need data of all mice in json format
        jsonAllMice = vizd.all_mice_gen()
        contextVars = {'jsonAllMice': jsonAllMice,
					   'curr_domain': request.get_host(),
                  'viewSelection': 'stats'}
        return render(request, 'stats.html', contextVars)

edit_colony/templates/add_mouse.html
{% extends "mouse.html" %}

{% block addedFields %}
<p>
	<label for="id_tod">Date of birth:</label>
	<input type="text" id="id_dob">
</p>
{% endblock %}

{% block submit %}
<input type="submit" value="Submit" />

<input type="button" value="Cancel" />
{% endblock %}

edit_colony/templates/edit_mouse.html
{% extends "mouse.html" %}


{% block addedFields %}
<p>
	{{ form.errors.tod }}
	<label for="id_tod">Time of death:</label>
	{{ form.tod }}
</p>
{% endblock %}

{% block submit %}
<input type="submit" value="Submit" />
<input type="button" value="Cancel" />
{% endblock %}

edit_colony/templates/find_edit.html
{% extends "find_mouse.html" %}

<!-- Parent template requires the variable iSrc -->

{% block title %}
<p class="caption">Edit a Mouse</p>
{% endblock %}

edit_colony/templates/find_mouse.html
<!DOCTYPE html>

<html>

<head>

<script src="/static/jquery-2.0.3.min.js"></script>
<link rel="stylesheet" type="text/css" href="/static/form.css">

<script>

    var submit_fxn = function() {
            if ($("#txtMouse").val()) {
                if ($("#editsection").find("iframe").length > 0) {
                    //var ifrSource = '/edit_colony/edit_mouse/?mouseId=' + $("#txtMouse").val();
                    var ifrSource = '{{ iSrc }}?mouseId=' + $("#txtMouse").val();
                    $("#editsection").find("iframe").attr("src", ifrSource);
                }
                else {
                    $("#editsection").append('<iframe src="{{ iSrc }}?mouseId=' +
                        $("#txtMouse").val() + '" height="400" width="100%"></iframe>');
                }
            }
    }

    $(document).ready( function() {
        $("#btnMouse").click(submit_fxn );
        $('#txtMouse').bind('keydown', function(e) {
            if (e.which == 13) { // 'Enter' key pressed
                submit_fxn();
            }
        });
    });
</script>

</head>

{% block title %}
{% endblock %}

<div class="editField">
	<p id="primaryId">
		<label>Mouse ID:</label>
        <input id="txtMouse" type="text" />
        <input id="btnMouse" type="button" value="Find"/>
	</p>
</div>

<div id="editsection">
</div>

</html>

edit_colony/templates/mouse.html
<!DOCTYPE html>

<html>

<head>

<script src="/static/jquery-2.0.3.min.js"></script>
<script>
	// This script needs to execute before the jeasyui sourced scripts
	// for the dynamic options to appear in dropdown list
	$(document).ready( function() {
		// remove bullets from auto created list for RadioSelect
		$("div.genotype ul").each( function() {
			$(this).css("list-style-type","none")
			});

		// dynamically created options for gene select
		$(".easyui-combobox").each( function() {
            var selectedVal;
            // Pre-select the option stored in the template's context variable
            if( $(this).attr("name") == "gene1") {
                selectedVal = "{{ gene1Val }}";
            }
            else if( $(this).attr("name") == "gene2") {
                selectedVal = "{{ gene2Val }}";
            }
            else if( $(this).attr("name") == "gene3") {
                selectedVal = "{{ gene3Val }}";
            }
			{% for gene in geneList %}
                if( "{{gene}}" == selectedVal ) {
			        $(this).append('<option value="{{gene}}" selected>{{gene}}</option>');
                }
                else {
                    $(this).append('<option value="{{gene}}">{{gene}}</option>');
                }
			{% endfor %}
			});
	});
</script>
<link rel="stylesheet" type="text/css" href="http://www.jeasyui.com/easyui/themes/default/easyui.css">
<link rel="stylesheet" type="text/css" href="http://www.jeasyui.com/easyui/themes/icon.css">
<link rel="stylesheet" type="text/css" href="http://www.jeasyui.com/easyui/demo/demo.css">
<script type="text/javascript" src="http://www.jeasyui.com/easyui/jquery.easyui.min.js"></script>

{% block jshead %}
{% endblock %}

</head>

<body>

<link rel="stylesheet" type="text/css" href="/static/form.css">
<form action={{ submitAction }} method="post">
{% csrf_token %}



<div class="editField">
	<p>
		<label class="fielderror">{{ form.mouseId.errors }}</label>
		<label for="id_mouseId">Mouse ID:</label>
		{{ form.mouseId }}
		<label class="fielderror">{{ form.gender.errors }}</label>
		<label for="id_gender">Gender:</label>
		{{ form.gender}}
	</p>
	<p>
		<label class="fielderror">{{ form.fatherId.errors }}</label>
		<label for="id_fatherId">Father ID:</label>
		{{ form.fatherId}}
		<label class="fielderror">{{ form.motherId.errors }}</label>
		<label for="id_motherId">Mother ID:</label>
		{{ form.motherId}}
		<label class="fielderror">{{ form.litter.errors }}</label>
		<label for="id_litter">Litter:</label>
		{{ form.litter}}
	</p>
	<p>
		<label class="fielderror">{{ form.notes.errors }}</label>
		<label for="id_notes">Notes:</label>
		{{ form.notes}}
	</p>
	<p>
	<table>
	  <tr>
	    <td>
		{% block geneInput1 %}
		<label class="fielderror">{{ form.errors.gene1 }}</label>
		<label for="id_gene1">Gene 1:</label>
		{{ form.gene1 }}
		{% endblock %}
	    </td>
	    <td>
		{% block geneInput2 %}
		<label class="fielderror">{{ form.errors.gene2 }}</label>
		<label for="id_gene2">Gene 2:</label>
		{{ form.gene2 }}
		{% endblock %}
	    </td>
	    <td>
		{% block geneInput3 %}
		<label class="fielderror">{{ form.errors.gene3 }}</label>
		<label for="id_gene3">Gene 3:</label>
		{{ form.gene3 }}
		{% endblock %}
	    </td>
	  </tr>
	  <tr><td><div class="genotype">
		{% block genotype1 %}
		{{ form.genotype1 }}
		{% endblock %}
	     </div></td>
	     <td><div class="genotype">
		{% block genotype2 %}
		{{ form.genotype2 }}
		{% endblock %}
	     </div></td>
	     <td><div class="genotype">
		{% block genotype3 %}
		{{ form.genotype3 }}
		{% endblock %}
	  </div></td></tr>
	</table>
	</p>
</div>
{% block addedFields %}
{% endblock %}
{% block submit %}
<input type="submit" value="Submit" />
{% endblock %}
</form>

</body>
</html>

edit_colony/templates/validate_mouse.html
{% extends "mouse.html" %}

{% block addedFields %}
<p>
	<label for="id_tod">Date of birth:</label>
	<input type="text" id="id_dob">
</p>
{% endblock %}

{% block submit %}
<input type="submit" value="Submit" />

<input type="button" value="Cancel" />
{% endblock %}